
# █▄▀ █▀▀ █▄█ █▄▄ █ █▄░█ █▀▄ █ █▄░█ █▀▀ █▀
# █░█ ██▄ ░█░ █▄█ █ █░▀█ █▄▀ █ █░▀█ █▄█ ▄█


# See https://wiki.hyprland.org/Configuring/Keywords/ for more
# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more

# main modifier
$mainMod = super

# window/session actions
bind = $mainMod, q, killactive, # kill active window
bind = $mainMod, space, togglefloating, # toggle the window on focus to float
bind = $mainMod, f, fullscreen, # toggle the window on focus to fullscreen
bind = $mainMod, escape, exec, hyprlock 
bind = $mainMod alt, escape, exec, hyprctl keyword monitor "HDMI-A-1,preferred, 0x0, 1" # after suspend ,monitor stuck fix

# Launch terminal
bind = $mainMod, RETURN, exec, foot

# App launcher
bind = $mainMod, super_l, exec, rofi -show drun

# File manager
bind = $mainMod, e, exec, nautilus

# Browser
bind = $mainMod, b, exec, google-chrome-stable

# Screenshot (using grim + slurp)
bind = , Print, exec, grimblast copy area

# Toggle waybar
bind = $mainMod, w, exec, pkill -SIGUSR1 waybar

# audio control
bind = ,XF86AudioRaiseVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ +5%
bind = ,XF86AudioLowerVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ -5%
bind = ,XF86AudioMute, exec, pactl set-sink-mute @DEFAULT_SINK@ toggle

# brightness control
binde = , XF86MonBrightnessUp, exec, brightnessctl s +10%
binde = , XF86MonBrightnessDown, exec, brightnessctl s 10%-

# Media playback
bind = , XF86AudioPlay, exec, playerctl play-pause
bind = , XF86AudioNext, exec, playerctl next
bind = , XF86AudioPrev, exec, playerctl previous

# Move focus between windows
bind = $mainMod, h, movefocus, l
bind = $mainMod, l, movefocus, r
bind = $mainMod, k, movefocus, u
bind = $mainMod, j, movefocus, d

# Move windows
bind = $mainMod shift, h, movewindow, l
bind = $mainMod shift, l, movewindow, r
bind = $mainMod shift, k, movewindow, u
bind = $mainMod shift, j, movewindow, d

# Switch workspaces
bind = alt, 1, workspace, 1
bind = alt, 2, workspace, 2
bind = alt, 3, workspace, 3
bind = alt, 4, workspace, 4
bind = alt, 5, workspace, 5
bind = alt, 6, workspace, 6
bind = alt, 7, workspace, 7
bind = alt, 8, workspace, 8
bind = alt, 9, workspace, 9
bind = alt, 0, workspace, 0

# Move active window to workspace
bind = $mainMod alt, 1, movetoworkspace, 1
bind = $mainMod alt, 2, movetoworkspace, 2
bind = $mainMod alt, 3, movetoworkspace, 3
bind = $mainMod alt, 4, movetoworkspace, 4
bind = $mainMod alt, 5, movetoworkspace, 5
bind = $mainMod alt, 6, movetoworkspace, 6
bind = $mainMod alt, 7, movetoworkspace, 7
bind = $mainMod alt, 8, movetoworkspace, 8
bind = $mainMod alt, 9, movetoworkspace, 9
bind = $mainMod alt, 10, movetoworkspace, 10

# --- Move and resize windows ---
# Move window with $mainMod + Left click
bindm = $mainMod, mouse:272, movewindow

# Resize window with $mainMod + Right click
bindm = $mainMod, mouse:273, resizewindow

