monitor=eDP-1,preferred,1920x0,1.0
monitor=HDMI-A-1,preferred,0x0,1.0

workspace = 1, monitor:eDP-1, persistent:true

# 2. Force Workspaces 2-10 to External (HDMI-A-1)
# If HDMI is NOT plugged in, Hyprland ignores these rules
# and behaves normally (workspaces appear on eDP-1).
workspace = 2, monitor:HDMI-A-1, default:true
workspace = 3, monitor:HDMI-A-1, default:true
workspace = 4, monitor:HDMI-A-1, default:true
workspace = 5, monitor:HDMI-A-1, default:true
workspace = 6, monitor:HDMI-A-1, default:true
workspace = 7, monitor:HDMI-A-1, default:true
workspace = 8, monitor:HDMI-A-1, default:true
workspace = 9, monitor:HDMI-A-1, default:true
workspace = 10, monitor:HDMI-A-1, default:true
